### ISSUE TITLE
Items duplication

### ISSUE THREAD

**Issue by Sandile-Dev01** [koheinthurako/E-commerce_website_project#1]
The project is clean and I love the animations when you add the item in the cart.

- But I found a bug, I feel like the app would be more robust if it allowed the user to only add the item once on the cart and than increment or decrement the number of items when the cart component is viewed.

**Comment by koheinthurako** [comment]
> The project is clean and I love the animations when you add the item in the cart.
> 
> - But I found a bug, I feel like the app would be more robust if it allowed the user to only add the item once on the cart and than increment or decrement the number of items when the cart component is viewed.

"Thank you for your appreciation and advice. This project is just for testing. I have found a lot of bugs in it."
